
services:
    backend:
      build: ./server
      container_name: backend
      ports:
        - '5000:5000'
      environment:
        - MONGO_URI=mongodb+srv://priyanshuvatsyan:TcgPsmIYqAt9f3A0@timemanagementsystem.kl0mkjl.mongodb.net/
        - PORT=5000
        - JWT_SECRET=tms
      volumes:
        - ./server:/app

    frontend:
      build: ./client
      container_name: frontend
      ports:
        - '3000:80'
      depends_on:
        - backend
      environment:
        - VITE_API_URL=http://localhost:5000